version: '3'
services:
  chat_client:
    container_name: chat_llm
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: chat_llm:0.0.2
    env_file:
      - .env
    volumes:
      - $PWD/data/store:/opt/data/store
    ports:
      - "9998:9999" # host:container
