version: '3'
services:
  chat_client:
    container_name: chat_llm
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: chat_llm:0.0.2
    env_file:
      - .env
    ports:
      - "9998:9999" # host:container:

#  qdrant_client:
#    container_name: qdrant_embedding
#    image: qdrant/qdrant:latest
#    volumes:
#      - $PWD/qdrant:/store/storage/store
#    ports:
#      - "6333:6333"
